<%--
  Created by IntelliJ IDEA.
  User: wyjianglubin
  Date: 2014/5/20
  Time: 11:21
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<jsp:include page="../head.jsp" />
<div class="container">
<div class="row container-main">
<div class="col-xs-2 container-main_menu">
    <div class="menu-filter">

        <div class="form-group">
            <input id="J_filter" type="text" class="form-control" placeholder="Filter" />
        </div>
    </div>

    <div class="menu">
        <div id="J_navnew">
            <ul class="navnew">
                <li class="navnew-item ">
                    <a class="item-link" href="<%=request.getContextPath() %>/web-qm/mysql.jsp" title="总览">总览</a>
                </li>
                <li class="navnew-item  active ignore ">
                    <a class="item-link dbItemLink" href="<%=request.getContextPath() %>/web-qm/database/instance_mysql.jsp" title="WYCDS_MySQL" data-sid="285" data-dbtype="MySQL" data-dbrole="primary">
                        <span class="badge identifying-master">主</span>
                        WYCDS_MySQL
                    </a>
                </li>
                <li class="navnew-item ">
                    <a class="item-link dbItemLink" href="" title="mysql_240_5.1" data-sid="267" data-dbtype="MySQL" data-dbrole="primary">
                        <span class="badge identifying-master">主</span>
                        mysql_240_5.1
                    </a>
                </li>
                <li class="navnew-item ">
                    <a class="item-link dbItemLink" href="" title="mysql_240_5.5" data-sid="268" data-dbtype="MySQL" data-dbrole="primary">
                        <span class="badge identifying-master">主</span>
                        mysql_240_5.5
                    </a>
                </li>
                <li class="navnew-item ">
                    <a class="item-link dbItemLink" href="" title="mysql_240_5.6" data-sid="269" data-dbtype="MySQL" data-dbrole="primary">
                        <span class="badge identifying-master">主</span>
                        mysql_240_5.6
                    </a>
                </li>
            </ul>
        </div>

    </div>

</div><!--/sub menu -->

<div class="col-xs-10 container-main_content">
<input type="hidden" id="ID-sid" value="285" />
<input type="hidden" id="ID-dbname" value="WYCDS_MySQL" />
<input type="hidden" id="ID-dbtype" value="MySQL" />
<div class="row tabs-wrap">

    <div class="col-xs-10">
        <ul class="nav nav-tabs">
            <li  class="active" >
                <a href="<%=request.getContextPath() %>/web-qm/database/instance_mysql.jsp">数据库信息</a>
            </li>
            <li >
                <a href="<%=request.getContextPath() %>/web-qm/performance/my/top-sql.jsp">TOP SQL</a>
            </li>
            <li >
                <a href="<%=request.getContextPath() %>/web-qm/space/home_mysql.jsp">空间</a>
            </li>
        </ul>
    </div>


</div>


<div class="row">
    <div class="col-xs-6">
        <div class="panel panel-default transparent">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="icon-info-sign"></i>基本信息</h3>
                <div class="panel-toolbar">
                    <a data-toggle="collapse" href="#J_databaseInfo">
                        <i class="icon-chevron-up"></i>
                    </a>
                </div>
            </div>
            <div id="J_databaseInfo" class="panel-collapse collapse in">
                <div class="panel-body">
                    <table class="table table-bordered table-striped databaseInfo">
                        <tbody>
                        <tr>
                            <td class="title">数据库名称</td>
                            <td>
                                <div id="ID-editNameWrap" class="rac-info-editName-wrap">
                                    WYCDS_MySQL
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="title">IP</td>
                            <td>192.168.1.204</td>
                        </tr>
                        <tr>
                            <td class="title">角色</td>
                            <td> 主库 </td>
                        </tr>
                        <tr>
                            <td class="title">端口</td>
                            <td>3306</td>
                        </tr>
                        <tr>
                            <td class="title">类型 / 版本</td>
                            <td>MySQL / 5.5.25a-log Source distribution</td>
                        </tr>
                        <tr>
                            <td class="title">性能采集状态</td>
                            <td>
                                <span class="label label-state b-success">已开启</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="title">在线状态</td>
                            <td>
                                <span class="label label-state b-success">线上</span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-6">
        <div class="panel panel-default transparent">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="icon-info-sign"></i>主机信息</h3>
                <div class="panel-toolbar">
                    <a data-toggle="collapse" href="#J_databaseHostInfo">
                        <i class="icon-chevron-up"></i>
                    </a>
                </div>
            </div>
            <div id="J_databaseHostInfo" class="panel-collapse collapse in">
                <div class="panel-body">
                    <table class="table table-bordered table-striped databaseInfo">
                        <tbody>
                        <tr>
                            <td class="title">名称</td>
                            <td>
                                <a href="<%=request.getContextPath() %>/web-qm/host/instance_mysql.jsp">multi-mysql</a>
                            </td>
                        </tr>
                        <tr>
                            <td class="title">主机 IP</td>
                            <td>192.168.1.204</td>
                        </tr>
                        <tr>
                            <td class="title">内存(GB)</td>
                            <td>16</td>
                        </tr>
                        <tr>
                            <td class="title">系统 / 内核 / 版本</td>
                            <td>Linux / 2.6.32-220.el6.x86_64 / Red Hat Enterprise Linux Server release 6.2 (Santiago)</td>
                        </tr>
                        <tr>
                            <td class="title">CPU频率 / 核数 / 厂商</td>
                            <td>0.78 / 4 / Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz</td>
                        </tr>
                        <tr>
                            <td class="title">性能采集状态</td>
                            <td>
                                <span class="label label-state b-success">已开启</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="title">在线状态</td>
                            <td>
                                <span class="label label-state b-success">线上</span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-6">
        <div class="panel panel-default transparent">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="icon-dashboard"></i>CPU(us+sys+iowait)</h3>
                <div class="panel-toolbar no-border">Last 1 hour</div>
                <div class="panel-toolbar">
                    <a data-toggle="collapse" href="#J_databaseDashboard">
                        <i class="icon-chevron-up"></i>
                    </a>
                </div>
            </div>
            <div id="J_databaseDashboard" class="panel-collapse collapse in">
                <div class="panel-body">
                    <div class="database-dashboard chartContainer" data-vid="284" data-title="CPU" data-loadurl="<%=request.getContextPath() %>/web-qm/load-cpu-quota.htm" data-chartData="[{&quot;calValue&quot;:11,&quot;gmtCreate&quot;:1400552460000,&quot;selected&quot;:false,&quot;x&quot;:1400552460000,&quot;y&quot;:11},{&quot;calValue&quot;:7,&quot;gmtCreate&quot;:1400552520000,&quot;selected&quot;:false,&quot;x&quot;:1400552520000,&quot;y&quot;:7},{&quot;calValue&quot;:19,&quot;gmtCreate&quot;:1400552580000,&quot;selected&quot;:false,&quot;x&quot;:1400552580000,&quot;y&quot;:19},{&quot;calValue&quot;:5,&quot;gmtCreate&quot;:1400552640000,&quot;selected&quot;:false,&quot;x&quot;:1400552640000,&quot;y&quot;:5},{&quot;calValue&quot;:12,&quot;gmtCreate&quot;:1400552700000,&quot;selected&quot;:false,&quot;x&quot;:1400552700000,&quot;y&quot;:12},{&quot;calValue&quot;:9,&quot;gmtCreate&quot;:1400552760000,&quot;selected&quot;:false,&quot;x&quot;:1400552760000,&quot;y&quot;:9},{&quot;calValue&quot;:5,&quot;gmtCreate&quot;:1400552820000,&quot;selected&quot;:false,&quot;x&quot;:1400552820000,&quot;y&quot;:5},{&quot;calValue&quot;:16,&quot;gmtCreate&quot;:1400552880000,&quot;selected&quot;:false,&quot;x&quot;:1400552880000,&quot;y&quot;:16},{&quot;calValue&quot;:10,&quot;gmtCreate&quot;:1400552940000,&quot;selected&quot;:false,&quot;x&quot;:1400552940000,&quot;y&quot;:10},{&quot;calValue&quot;:98,&quot;gmtCreate&quot;:1400553000000,&quot;selected&quot;:false,&quot;x&quot;:1400553000000,&quot;y&quot;:98},{&quot;calValue&quot;:9,&quot;gmtCreate&quot;:1400553060000,&quot;selected&quot;:false,&quot;x&quot;:1400553060000,&quot;y&quot;:9},{&quot;calValue&quot;:7,&quot;gmtCreate&quot;:1400553120000,&quot;selected&quot;:false,&quot;x&quot;:1400553120000,&quot;y&quot;:7},{&quot;calValue&quot;:12,&quot;gmtCreate&quot;:1400553180000,&quot;selected&quot;:false,&quot;x&quot;:1400553180000,&quot;y&quot;:12},{&quot;calValue&quot;:7,&quot;gmtCreate&quot;:1400553240000,&quot;selected&quot;:false,&quot;x&quot;:1400553240000,&quot;y&quot;:7},{&quot;calValue&quot;:6,&quot;gmtCreate&quot;:1400553300000,&quot;selected&quot;:false,&quot;x&quot;:1400553300000,&quot;y&quot;:6},{&quot;calValue&quot;:10,&quot;gmtCreate&quot;:1400553360000,&quot;selected&quot;:false,&quot;x&quot;:1400553360000,&quot;y&quot;:10},{&quot;calValue&quot;:6,&quot;gmtCreate&quot;:1400553420000,&quot;selected&quot;:false,&quot;x&quot;:1400553420000,&quot;y&quot;:6},{&quot;calValue&quot;:28,&quot;gmtCreate&quot;:1400553480000,&quot;selected&quot;:false,&quot;x&quot;:1400553480000,&quot;y&quot;:28},{&quot;calValue&quot;:25,&quot;gmtCreate&quot;:1400553540000,&quot;selected&quot;:false,&quot;x&quot;:1400553540000,&quot;y&quot;:25},{&quot;calValue&quot;:6,&quot;gmtCreate&quot;:1400553600000,&quot;selected&quot;:false,&quot;x&quot;:1400553600000,&quot;y&quot;:6},{&quot;calValue&quot;:7,&quot;gmtCreate&quot;:1400553660000,&quot;selected&quot;:false,&quot;x&quot;:1400553660000,&quot;y&quot;:7},{&quot;calValue&quot;:4,&quot;gmtCreate&quot;:1400553720000,&quot;selected&quot;:false,&quot;x&quot;:1400553720000,&quot;y&quot;:4},{&quot;calValue&quot;:10,&quot;gmtCreate&quot;:1400553780000,&quot;selected&quot;:false,&quot;x&quot;:1400553780000,&quot;y&quot;:10},{&quot;calValue&quot;:6,&quot;gmtCreate&quot;:1400553840000,&quot;selected&quot;:false,&quot;x&quot;:1400553840000,&quot;y&quot;:6},{&quot;calValue&quot;:6,&quot;gmtCreate&quot;:1400553900000,&quot;selected&quot;:false,&quot;x&quot;:1400553900000,&quot;y&quot;:6},{&quot;calValue&quot;:5,&quot;gmtCreate&quot;:1400553960000,&quot;selected&quot;:false,&quot;x&quot;:1400553960000,&quot;y&quot;:5},{&quot;calValue&quot;:5,&quot;gmtCreate&quot;:1400554020000,&quot;selected&quot;:false,&quot;x&quot;:1400554020000,&quot;y&quot;:5},{&quot;calValue&quot;:25,&quot;gmtCreate&quot;:1400554080000,&quot;selected&quot;:false,&quot;x&quot;:1400554080000,&quot;y&quot;:25},{&quot;calValue&quot;:7,&quot;gmtCreate&quot;:1400554140000,&quot;selected&quot;:false,&quot;x&quot;:1400554140000,&quot;y&quot;:7},{&quot;calValue&quot;:14,&quot;gmtCreate&quot;:1400554200000,&quot;selected&quot;:false,&quot;x&quot;:1400554200000,&quot;y&quot;:14},{&quot;calValue&quot;:5,&quot;gmtCreate&quot;:1400554260000,&quot;selected&quot;:false,&quot;x&quot;:1400554260000,&quot;y&quot;:5},{&quot;calValue&quot;:3,&quot;gmtCreate&quot;:1400554320000,&quot;selected&quot;:false,&quot;x&quot;:1400554320000,&quot;y&quot;:3},{&quot;calValue&quot;:34,&quot;gmtCreate&quot;:1400554380000,&quot;selected&quot;:false,&quot;x&quot;:1400554380000,&quot;y&quot;:34},{&quot;calValue&quot;:5,&quot;gmtCreate&quot;:1400554440000,&quot;selected&quot;:false,&quot;x&quot;:1400554440000,&quot;y&quot;:5},{&quot;calValue&quot;:4,&quot;gmtCreate&quot;:1400554500000,&quot;selected&quot;:false,&quot;x&quot;:1400554500000,&quot;y&quot;:4},{&quot;calValue&quot;:5,&quot;gmtCreate&quot;:1400554560000,&quot;selected&quot;:false,&quot;x&quot;:1400554560000,&quot;y&quot;:5},{&quot;calValue&quot;:24,&quot;gmtCreate&quot;:1400554620000,&quot;selected&quot;:false,&quot;x&quot;:1400554620000,&quot;y&quot;:24},{&quot;calValue&quot;:26,&quot;gmtCreate&quot;:1400554680000,&quot;selected&quot;:false,&quot;x&quot;:1400554680000,&quot;y&quot;:26},{&quot;calValue&quot;:6,&quot;gmtCreate&quot;:1400554740000,&quot;selected&quot;:false,&quot;x&quot;:1400554740000,&quot;y&quot;:6},{&quot;calValue&quot;:98,&quot;gmtCreate&quot;:1400554800000,&quot;selected&quot;:false,&quot;x&quot;:1400554800000,&quot;y&quot;:98},{&quot;calValue&quot;:17,&quot;gmtCreate&quot;:1400554860000,&quot;selected&quot;:false,&quot;x&quot;:1400554860000,&quot;y&quot;:17},{&quot;calValue&quot;:6,&quot;gmtCreate&quot;:1400554920000,&quot;selected&quot;:false,&quot;x&quot;:1400554920000,&quot;y&quot;:6},{&quot;calValue&quot;:3,&quot;gmtCreate&quot;:1400554980000,&quot;selected&quot;:false,&quot;x&quot;:1400554980000,&quot;y&quot;:3},{&quot;calValue&quot;:7,&quot;gmtCreate&quot;:1400555040000,&quot;selected&quot;:false,&quot;x&quot;:1400555040000,&quot;y&quot;:7},{&quot;calValue&quot;:5,&quot;gmtCreate&quot;:1400555100000,&quot;selected&quot;:false,&quot;x&quot;:1400555100000,&quot;y&quot;:5},{&quot;calValue&quot;:22,&quot;gmtCreate&quot;:1400555160000,&quot;selected&quot;:false,&quot;x&quot;:1400555160000,&quot;y&quot;:22},{&quot;calValue&quot;:15,&quot;gmtCreate&quot;:1400555220000,&quot;selected&quot;:false,&quot;x&quot;:1400555220000,&quot;y&quot;:15},{&quot;calValue&quot;:18,&quot;gmtCreate&quot;:1400555280000,&quot;selected&quot;:false,&quot;x&quot;:1400555280000,&quot;y&quot;:18},{&quot;calValue&quot;:8,&quot;gmtCreate&quot;:1400555340000,&quot;selected&quot;:false,&quot;x&quot;:1400555340000,&quot;y&quot;:8},{&quot;calValue&quot;:5,&quot;gmtCreate&quot;:1400555400000,&quot;selected&quot;:false,&quot;x&quot;:1400555400000,&quot;y&quot;:5},{&quot;calValue&quot;:16,&quot;gmtCreate&quot;:1400555460000,&quot;selected&quot;:false,&quot;x&quot;:1400555460000,&quot;y&quot;:16},{&quot;calValue&quot;:7,&quot;gmtCreate&quot;:1400555520000,&quot;selected&quot;:false,&quot;x&quot;:1400555520000,&quot;y&quot;:7},{&quot;calValue&quot;:10,&quot;gmtCreate&quot;:1400555580000,&quot;selected&quot;:false,&quot;x&quot;:1400555580000,&quot;y&quot;:10},{&quot;calValue&quot;:6,&quot;gmtCreate&quot;:1400555640000,&quot;selected&quot;:false,&quot;x&quot;:1400555640000,&quot;y&quot;:6},{&quot;calValue&quot;:4,&quot;gmtCreate&quot;:1400555700000,&quot;selected&quot;:false,&quot;x&quot;:1400555700000,&quot;y&quot;:4},{&quot;calValue&quot;:17,&quot;gmtCreate&quot;:1400555760000,&quot;selected&quot;:false,&quot;x&quot;:1400555760000,&quot;y&quot;:17},{&quot;calValue&quot;:6,&quot;gmtCreate&quot;:1400555820000,&quot;selected&quot;:false,&quot;x&quot;:1400555820000,&quot;y&quot;:6},{&quot;calValue&quot;:10,&quot;gmtCreate&quot;:1400555880000,&quot;selected&quot;:false,&quot;x&quot;:1400555880000,&quot;y&quot;:10},{&quot;calValue&quot;:12,&quot;gmtCreate&quot;:1400555940000,&quot;selected&quot;:false,&quot;x&quot;:1400555940000,&quot;y&quot;:12},{&quot;calValue&quot;:4,&quot;gmtCreate&quot;:1400556000000,&quot;selected&quot;:false,&quot;x&quot;:1400556000000,&quot;y&quot;:4}]" data-nodata="当前MySQL数据库所在的主机没有CPU信息，请检查主机的性能采集状态。" style="height: 200px;"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-6">
        <div class="panel panel-default transparent">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="icon-random"></i>Load</h3>
                <div class="panel-toolbar no-border">Last 1 hour</div>
                <div class="panel-toolbar">
                    <a data-toggle="collapse" href="#J_databaseLoad">
                        <i class="icon-chevron-up"></i>
                    </a>
                </div>
            </div>
            <div id="J_databaseLoad" class="panel-collapse collapse in">
                <div class="panel-body">
                    <div class="database-load chartContainer" data-sid="284" data-statid="1" data-statidName="Load" data-loadurl="<%=request.getContextPath() %>/web-qm/performance/quota/chart/load-quotas-point-data.htm" data-chartdata="[{&quot;calValue&quot;:0.74,&quot;gmtCreate&quot;:1400552460000,&quot;selected&quot;:false,&quot;x&quot;:1400552460000,&quot;y&quot;:0.74},{&quot;calValue&quot;:0.41,&quot;gmtCreate&quot;:1400552520000,&quot;selected&quot;:false,&quot;x&quot;:1400552520000,&quot;y&quot;:0.41},{&quot;calValue&quot;:0.4,&quot;gmtCreate&quot;:1400552580000,&quot;selected&quot;:false,&quot;x&quot;:1400552580000,&quot;y&quot;:0.4},{&quot;calValue&quot;:0.54,&quot;gmtCreate&quot;:1400552640000,&quot;selected&quot;:false,&quot;x&quot;:1400552640000,&quot;y&quot;:0.54},{&quot;calValue&quot;:1.28,&quot;gmtCreate&quot;:1400552700000,&quot;selected&quot;:false,&quot;x&quot;:1400552700000,&quot;y&quot;:1.28},{&quot;calValue&quot;:0.57,&quot;gmtCreate&quot;:1400552760000,&quot;selected&quot;:false,&quot;x&quot;:1400552760000,&quot;y&quot;:0.57},{&quot;calValue&quot;:0.43,&quot;gmtCreate&quot;:1400552820000,&quot;selected&quot;:false,&quot;x&quot;:1400552820000,&quot;y&quot;:0.43},{&quot;calValue&quot;:0.22,&quot;gmtCreate&quot;:1400552880000,&quot;selected&quot;:false,&quot;x&quot;:1400552880000,&quot;y&quot;:0.22},{&quot;calValue&quot;:0.16,&quot;gmtCreate&quot;:1400552940000,&quot;selected&quot;:false,&quot;x&quot;:1400552940000,&quot;y&quot;:0.16},{&quot;calValue&quot;:1.03,&quot;gmtCreate&quot;:1400553000000,&quot;selected&quot;:false,&quot;x&quot;:1400553000000,&quot;y&quot;:1.03},{&quot;calValue&quot;:2.23,&quot;gmtCreate&quot;:1400553060000,&quot;selected&quot;:false,&quot;x&quot;:1400553060000,&quot;y&quot;:2.23},{&quot;calValue&quot;:1,&quot;gmtCreate&quot;:1400553120000,&quot;selected&quot;:false,&quot;x&quot;:1400553120000,&quot;y&quot;:1},{&quot;calValue&quot;:0.44,&quot;gmtCreate&quot;:1400553180000,&quot;selected&quot;:false,&quot;x&quot;:1400553180000,&quot;y&quot;:0.44},{&quot;calValue&quot;:0.43,&quot;gmtCreate&quot;:1400553240000,&quot;selected&quot;:false,&quot;x&quot;:1400553240000,&quot;y&quot;:0.43},{&quot;calValue&quot;:0.3,&quot;gmtCreate&quot;:1400553300000,&quot;selected&quot;:false,&quot;x&quot;:1400553300000,&quot;y&quot;:0.3},{&quot;calValue&quot;:0.28,&quot;gmtCreate&quot;:1400553360000,&quot;selected&quot;:false,&quot;x&quot;:1400553360000,&quot;y&quot;:0.28},{&quot;calValue&quot;:0.45,&quot;gmtCreate&quot;:1400553420000,&quot;selected&quot;:false,&quot;x&quot;:1400553420000,&quot;y&quot;:0.45},{&quot;calValue&quot;:0.75,&quot;gmtCreate&quot;:1400553480000,&quot;selected&quot;:false,&quot;x&quot;:1400553480000,&quot;y&quot;:0.75},{&quot;calValue&quot;:0.35,&quot;gmtCreate&quot;:1400553540000,&quot;selected&quot;:false,&quot;x&quot;:1400553540000,&quot;y&quot;:0.35},{&quot;calValue&quot;:0.2,&quot;gmtCreate&quot;:1400553600000,&quot;selected&quot;:false,&quot;x&quot;:1400553600000,&quot;y&quot;:0.2},{&quot;calValue&quot;:0.3,&quot;gmtCreate&quot;:1400553660000,&quot;selected&quot;:false,&quot;x&quot;:1400553660000,&quot;y&quot;:0.3},{&quot;calValue&quot;:0.38,&quot;gmtCreate&quot;:1400553720000,&quot;selected&quot;:false,&quot;x&quot;:1400553720000,&quot;y&quot;:0.38},{&quot;calValue&quot;:0.2,&quot;gmtCreate&quot;:1400553780000,&quot;selected&quot;:false,&quot;x&quot;:1400553780000,&quot;y&quot;:0.2},{&quot;calValue&quot;:0.25,&quot;gmtCreate&quot;:1400553840000,&quot;selected&quot;:false,&quot;x&quot;:1400553840000,&quot;y&quot;:0.25},{&quot;calValue&quot;:0.16,&quot;gmtCreate&quot;:1400553900000,&quot;selected&quot;:false,&quot;x&quot;:1400553900000,&quot;y&quot;:0.16},{&quot;calValue&quot;:0.32,&quot;gmtCreate&quot;:1400553960000,&quot;selected&quot;:false,&quot;x&quot;:1400553960000,&quot;y&quot;:0.32},{&quot;calValue&quot;:0.45,&quot;gmtCreate&quot;:1400554020000,&quot;selected&quot;:false,&quot;x&quot;:1400554020000,&quot;y&quot;:0.45},{&quot;calValue&quot;:0.22,&quot;gmtCreate&quot;:1400554080000,&quot;selected&quot;:false,&quot;x&quot;:1400554080000,&quot;y&quot;:0.22},{&quot;calValue&quot;:0.36,&quot;gmtCreate&quot;:1400554140000,&quot;selected&quot;:false,&quot;x&quot;:1400554140000,&quot;y&quot;:0.36},{&quot;calValue&quot;:0.63,&quot;gmtCreate&quot;:1400554200000,&quot;selected&quot;:false,&quot;x&quot;:1400554200000,&quot;y&quot;:0.63},{&quot;calValue&quot;:0.53,&quot;gmtCreate&quot;:1400554260000,&quot;selected&quot;:false,&quot;x&quot;:1400554260000,&quot;y&quot;:0.53},{&quot;calValue&quot;:0.34,&quot;gmtCreate&quot;:1400554320000,&quot;selected&quot;:false,&quot;x&quot;:1400554320000,&quot;y&quot;:0.34},{&quot;calValue&quot;:0.35,&quot;gmtCreate&quot;:1400554380000,&quot;selected&quot;:false,&quot;x&quot;:1400554380000,&quot;y&quot;:0.35},{&quot;calValue&quot;:0.47,&quot;gmtCreate&quot;:1400554440000,&quot;selected&quot;:false,&quot;x&quot;:1400554440000,&quot;y&quot;:0.47},{&quot;calValue&quot;:0.34,&quot;gmtCreate&quot;:1400554500000,&quot;selected&quot;:false,&quot;x&quot;:1400554500000,&quot;y&quot;:0.34},{&quot;calValue&quot;:0.3,&quot;gmtCreate&quot;:1400554560000,&quot;selected&quot;:false,&quot;x&quot;:1400554560000,&quot;y&quot;:0.3},{&quot;calValue&quot;:0.38,&quot;gmtCreate&quot;:1400554620000,&quot;selected&quot;:false,&quot;x&quot;:1400554620000,&quot;y&quot;:0.38},{&quot;calValue&quot;:0.26,&quot;gmtCreate&quot;:1400554680000,&quot;selected&quot;:false,&quot;x&quot;:1400554680000,&quot;y&quot;:0.26},{&quot;calValue&quot;:0.4,&quot;gmtCreate&quot;:1400554740000,&quot;selected&quot;:false,&quot;x&quot;:1400554740000,&quot;y&quot;:0.4},{&quot;calValue&quot;:0.34,&quot;gmtCreate&quot;:1400554800000,&quot;selected&quot;:false,&quot;x&quot;:1400554800000,&quot;y&quot;:0.34},{&quot;calValue&quot;:2.02,&quot;gmtCreate&quot;:1400554860000,&quot;selected&quot;:false,&quot;x&quot;:1400554860000,&quot;y&quot;:2.02},{&quot;calValue&quot;:0.91,&quot;gmtCreate&quot;:1400554920000,&quot;selected&quot;:false,&quot;x&quot;:1400554920000,&quot;y&quot;:0.91},{&quot;calValue&quot;:0.62,&quot;gmtCreate&quot;:1400554980000,&quot;selected&quot;:false,&quot;x&quot;:1400554980000,&quot;y&quot;:0.62},{&quot;calValue&quot;:0.49,&quot;gmtCreate&quot;:1400555040000,&quot;selected&quot;:false,&quot;x&quot;:1400555040000,&quot;y&quot;:0.49},{&quot;calValue&quot;:0.37,&quot;gmtCreate&quot;:1400555100000,&quot;selected&quot;:false,&quot;x&quot;:1400555100000,&quot;y&quot;:0.37},{&quot;calValue&quot;:0.23,&quot;gmtCreate&quot;:1400555160000,&quot;selected&quot;:false,&quot;x&quot;:1400555160000,&quot;y&quot;:0.23},{&quot;calValue&quot;:0.25,&quot;gmtCreate&quot;:1400555220000,&quot;selected&quot;:false,&quot;x&quot;:1400555220000,&quot;y&quot;:0.25},{&quot;calValue&quot;:0.5,&quot;gmtCreate&quot;:1400555280000,&quot;selected&quot;:false,&quot;x&quot;:1400555280000,&quot;y&quot;:0.5},{&quot;calValue&quot;:0.36,&quot;gmtCreate&quot;:1400555340000,&quot;selected&quot;:false,&quot;x&quot;:1400555340000,&quot;y&quot;:0.36},{&quot;calValue&quot;:0.25,&quot;gmtCreate&quot;:1400555400000,&quot;selected&quot;:false,&quot;x&quot;:1400555400000,&quot;y&quot;:0.25},{&quot;calValue&quot;:0.19,&quot;gmtCreate&quot;:1400555460000,&quot;selected&quot;:false,&quot;x&quot;:1400555460000,&quot;y&quot;:0.19},{&quot;calValue&quot;:0.36,&quot;gmtCreate&quot;:1400555520000,&quot;selected&quot;:false,&quot;x&quot;:1400555520000,&quot;y&quot;:0.36},{&quot;calValue&quot;:0.25,&quot;gmtCreate&quot;:1400555580000,&quot;selected&quot;:false,&quot;x&quot;:1400555580000,&quot;y&quot;:0.25},{&quot;calValue&quot;:0.4,&quot;gmtCreate&quot;:1400555640000,&quot;selected&quot;:false,&quot;x&quot;:1400555640000,&quot;y&quot;:0.4},{&quot;calValue&quot;:0.27,&quot;gmtCreate&quot;:1400555700000,&quot;selected&quot;:false,&quot;x&quot;:1400555700000,&quot;y&quot;:0.27},{&quot;calValue&quot;:0.21,&quot;gmtCreate&quot;:1400555760000,&quot;selected&quot;:false,&quot;x&quot;:1400555760000,&quot;y&quot;:0.21},{&quot;calValue&quot;:0.15,&quot;gmtCreate&quot;:1400555820000,&quot;selected&quot;:false,&quot;x&quot;:1400555820000,&quot;y&quot;:0.15},{&quot;calValue&quot;:0.12,&quot;gmtCreate&quot;:1400555880000,&quot;selected&quot;:false,&quot;x&quot;:1400555880000,&quot;y&quot;:0.12},{&quot;calValue&quot;:0.51,&quot;gmtCreate&quot;:1400555940000,&quot;selected&quot;:false,&quot;x&quot;:1400555940000,&quot;y&quot;:0.51},{&quot;calValue&quot;:0.33,&quot;gmtCreate&quot;:1400556000000,&quot;selected&quot;:false,&quot;x&quot;:1400556000000,&quot;y&quot;:0.33}]" data-nodata="当前MySQL数据库所在的主机没有Load信息，请检查主机的性能采集状态。" style="height: 200px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="panel panel-default transparent">
<div class="panel-heading">
    <h3 class="panel-title"><i class="icon-reorder"></i>数据库参数</h3>
    <div class="panel-toolbar">
        <a data-toggle="collapse" href="#J_databaseParams">
            <i class="icon-chevron-up"></i>
        </a>
    </div>
</div>
<div id="J_databaseParams" class="panel-collapse collapse in">
<div class="panel-body">
<table class="table table-bordered table-striped table-condensed databaseParams" data-dbType="mysql">
<thead>
<tr>
    <th class="name">参数名</th>
    <th>参数值</th>
</tr>
</thead>
<tbody>
<tr>
    <td>
        autocommit
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        automatic_sp_privileges
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        auto_increment_increment
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        auto_increment_offset
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        back_log
    </td>
    <td>100</td>
</tr>
<tr>
    <td>
        basedir
    </td>
    <td>/home/woqu/woqu-dev-env/mysql5.5.25a</td>
</tr>
<tr>
    <td>
        big_tables
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        binlog_cache_size
    </td>
    <td>2097152</td>
</tr>
<tr>
    <td>
        binlog_direct_non_transactional_updates
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        binlog_format
    </td>
    <td>ROW</td>
</tr>
<tr>
    <td>
        binlog_stmt_cache_size
    </td>
    <td>32768</td>
</tr>
<tr>
    <td>
        bulk_insert_buffer_size
    </td>
    <td>8388608</td>
</tr>
<tr>
    <td>
        character_sets_dir
    </td>
    <td>/home/woqu/woqu-dev-env/mysql5.5.25a/share/charsets/</td>
</tr>
<tr>
    <td>
        character_set_client
    </td>
    <td>utf8</td>
</tr>
<tr>
    <td>
        character_set_connection
    </td>
    <td>utf8</td>
</tr>
<tr>
    <td>
        character_set_database
    </td>
    <td>utf8</td>
</tr>
<tr>
    <td>
        character_set_filesystem
    </td>
    <td>binary</td>
</tr>
<tr>
    <td>
        character_set_results
    </td>
    <td>utf8</td>
</tr>
<tr>
    <td>
        character_set_server
    </td>
    <td>utf8</td>
</tr>
<tr>
    <td>
        character_set_system
    </td>
    <td>utf8</td>
</tr>
<tr>
    <td>
        collation_connection
    </td>
    <td>utf8_general_ci</td>
</tr>
<tr>
    <td>
        collation_database
    </td>
    <td>utf8_bin</td>
</tr>
<tr>
    <td>
        collation_server
    </td>
    <td>utf8_bin</td>
</tr>
<tr>
    <td>
        completion_type
    </td>
    <td>NO_CHAIN</td>
</tr>
<tr>
    <td>
        concurrent_insert
    </td>
    <td>AUTO</td>
</tr>
<tr>
    <td>
        connect_timeout
    </td>
    <td>10</td>
</tr>
<tr>
    <td>
        datadir
    </td>
    <td>/home/woqu/data/mysqldata3306/</td>
</tr>
<tr>
    <td>
        datetime_format
    </td>
    <td>%Y-%m-%d %H:%i:%s</td>
</tr>
<tr>
    <td>
        date_format
    </td>
    <td>%Y-%m-%d</td>
</tr>
<tr>
    <td>
        default_storage_engine
    </td>
    <td>InnoDB</td>
</tr>
<tr>
    <td>
        default_week_format
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        delayed_insert_limit
    </td>
    <td>100</td>
</tr>
<tr>
    <td>
        delayed_insert_timeout
    </td>
    <td>300</td>
</tr>
<tr>
    <td>
        delayed_queue_size
    </td>
    <td>1000</td>
</tr>
<tr>
    <td>
        delay_key_write
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        div_precision_increment
    </td>
    <td>4</td>
</tr>
<tr>
    <td>
        engine_condition_pushdown
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        error_count
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        event_scheduler
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        expire_logs_days
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        external_user
    </td>
    <td></td>
</tr>
<tr>
    <td>
        flush
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        flush_time
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        foreign_key_checks
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        ft_boolean_syntax
    </td>
    <td>+ -&gt;&lt;()~*:&quot;&quot;&amp;|</td>
</tr>
<tr>
    <td>
        ft_max_word_len
    </td>
    <td>84</td>
</tr>
<tr>
    <td>
        ft_min_word_len
    </td>
    <td>4</td>
</tr>
<tr>
    <td>
        ft_query_expansion_limit
    </td>
    <td>20</td>
</tr>
<tr>
    <td>
        ft_stopword_file
    </td>
    <td>(built-in)</td>
</tr>
<tr>
    <td>
        general_log
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        general_log_file
    </td>
    <td>mysql-general.log</td>
</tr>
<tr>
    <td>
        group_concat_max_len
    </td>
    <td>1024</td>
</tr>
<tr>
    <td>
        have_compress
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        have_crypt
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        have_csv
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        have_dynamic_loading
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        have_geometry
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        have_innodb
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        have_ndbcluster
    </td>
    <td>NO</td>
</tr>
<tr>
    <td>
        have_openssl
    </td>
    <td>NO</td>
</tr>
<tr>
    <td>
        have_partitioning
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        have_profiling
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        have_query_cache
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        have_rtree_keys
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        have_ssl
    </td>
    <td>NO</td>
</tr>
<tr>
    <td>
        have_symlink
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        hostname
    </td>
    <td>multi-mysql</td>
</tr>
<tr>
    <td>
        identity
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        ignore_builtin_innodb
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        init_connect
    </td>
    <td></td>
</tr>
<tr>
    <td>
        init_file
    </td>
    <td></td>
</tr>
<tr>
    <td>
        init_slave
    </td>
    <td></td>
</tr>
<tr>
    <td>
        innodb_adaptive_flushing
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_adaptive_hash_index
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_additional_mem_pool_size
    </td>
    <td>20971520</td>
</tr>
<tr>
    <td>
        innodb_autoextend_increment
    </td>
    <td>8</td>
</tr>
<tr>
    <td>
        innodb_autoinc_lock_mode
    </td>
    <td>2</td>
</tr>
<tr>
    <td>
        innodb_buffer_pool_instances
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        innodb_buffer_pool_size
    </td>
    <td>8589934592</td>
</tr>
<tr>
    <td>
        innodb_change_buffering
    </td>
    <td>inserts</td>
</tr>
<tr>
    <td>
        innodb_checksums
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_commit_concurrency
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        innodb_concurrency_tickets
    </td>
    <td>500</td>
</tr>
<tr>
    <td>
        innodb_data_file_path
    </td>
    <td>ibdata1:2000M;ibdata2:10M:autoextend</td>
</tr>
<tr>
    <td>
        innodb_data_home_dir
    </td>
    <td>/home/woqu/data/mysqldata3306</td>
</tr>
<tr>
    <td>
        innodb_doublewrite
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_fast_shutdown
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        innodb_file_format
    </td>
    <td>Antelope</td>
</tr>
<tr>
    <td>
        innodb_file_format_check
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_file_format_max
    </td>
    <td>Antelope</td>
</tr>
<tr>
    <td>
        innodb_file_per_table
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_flush_log_at_trx_commit
    </td>
    <td>2</td>
</tr>
<tr>
    <td>
        innodb_flush_method
    </td>
    <td>O_DIRECT</td>
</tr>
<tr>
    <td>
        innodb_force_load_corrupted
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        innodb_force_recovery
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        innodb_io_capacity
    </td>
    <td>400</td>
</tr>
<tr>
    <td>
        innodb_large_prefix
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        innodb_locks_unsafe_for_binlog
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        innodb_lock_wait_timeout
    </td>
    <td>50</td>
</tr>
<tr>
    <td>
        innodb_log_buffer_size
    </td>
    <td>8388608</td>
</tr>
<tr>
    <td>
        innodb_log_files_in_group
    </td>
    <td>2</td>
</tr>
<tr>
    <td>
        innodb_log_file_size
    </td>
    <td>104857600</td>
</tr>
<tr>
    <td>
        innodb_log_group_home_dir
    </td>
    <td>/home/woqu/data/mysqldata3306</td>
</tr>
<tr>
    <td>
        innodb_max_dirty_pages_pct
    </td>
    <td>75</td>
</tr>
<tr>
    <td>
        innodb_max_purge_lag
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        innodb_mirrored_log_groups
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        innodb_old_blocks_pct
    </td>
    <td>37</td>
</tr>
<tr>
    <td>
        innodb_old_blocks_time
    </td>
    <td>1000</td>
</tr>
<tr>
    <td>
        innodb_open_files
    </td>
    <td>300</td>
</tr>
<tr>
    <td>
        innodb_purge_batch_size
    </td>
    <td>20</td>
</tr>
<tr>
    <td>
        innodb_purge_threads
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        innodb_random_read_ahead
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        innodb_read_ahead_threshold
    </td>
    <td>56</td>
</tr>
<tr>
    <td>
        innodb_read_io_threads
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        innodb_replication_delay
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        innodb_rollback_on_timeout
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_rollback_segments
    </td>
    <td>128</td>
</tr>
<tr>
    <td>
        innodb_spin_wait_delay
    </td>
    <td>6</td>
</tr>
<tr>
    <td>
        innodb_stats_method
    </td>
    <td>nulls_equal</td>
</tr>
<tr>
    <td>
        innodb_stats_on_metadata
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_stats_sample_pages
    </td>
    <td>8</td>
</tr>
<tr>
    <td>
        innodb_strict_mode
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_support_xa
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        innodb_sync_spin_loops
    </td>
    <td>30</td>
</tr>
<tr>
    <td>
        innodb_table_locks
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_thread_concurrency
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        innodb_thread_sleep_delay
    </td>
    <td>10000</td>
</tr>
<tr>
    <td>
        innodb_use_native_aio
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        innodb_use_sys_malloc
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        innodb_version
    </td>
    <td>1.1.8</td>
</tr>
<tr>
    <td>
        innodb_write_io_threads
    </td>
    <td>8</td>
</tr>
<tr>
    <td>
        insert_id
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        interactive_timeout
    </td>
    <td>2880000</td>
</tr>
<tr>
    <td>
        join_buffer_size
    </td>
    <td>4194304</td>
</tr>
<tr>
    <td>
        keep_files_on_create
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        key_buffer_size
    </td>
    <td>67108864</td>
</tr>
<tr>
    <td>
        key_cache_age_threshold
    </td>
    <td>300</td>
</tr>
<tr>
    <td>
        key_cache_block_size
    </td>
    <td>1024</td>
</tr>
<tr>
    <td>
        key_cache_division_limit
    </td>
    <td>100</td>
</tr>
<tr>
    <td>
        large_files_support
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        large_pages
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        large_page_size
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        last_insert_id
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        lc_messages
    </td>
    <td>en_US</td>
</tr>
<tr>
    <td>
        lc_messages_dir
    </td>
    <td>/home/woqu/woqu-dev-env/mysql5.5.25a/share/</td>
</tr>
<tr>
    <td>
        lc_time_names
    </td>
    <td>en_US</td>
</tr>
<tr>
    <td>
        license
    </td>
    <td>GPL</td>
</tr>
<tr>
    <td>
        local_infile
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        locked_in_memory
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        lock_wait_timeout
    </td>
    <td>31536000</td>
</tr>
<tr>
    <td>
        log
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        log_bin
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        log_bin_trust_function_creators
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        log_error
    </td>
    <td>/home/woqu/data/mysqldata3306/mysql-error.log</td>
</tr>
<tr>
    <td>
        log_output
    </td>
    <td>FILE</td>
</tr>
<tr>
    <td>
        log_queries_not_using_indexes
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        log_slave_updates
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        log_slow_queries
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        log_warnings
    </td>
    <td>2</td>
</tr>
<tr>
    <td>
        long_query_time
    </td>
    <td>0.001000</td>
</tr>
<tr>
    <td>
        lower_case_file_system
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        lower_case_table_names
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        low_priority_updates
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        max_allowed_packet
    </td>
    <td>134217728</td>
</tr>
<tr>
    <td>
        max_binlog_cache_size
    </td>
    <td>18446744073709547520</td>
</tr>
<tr>
    <td>
        max_binlog_size
    </td>
    <td>1073741824</td>
</tr>
<tr>
    <td>
        max_binlog_stmt_cache_size
    </td>
    <td>18446744073709547520</td>
</tr>
<tr>
    <td>
        max_connections
    </td>
    <td>2000</td>
</tr>
<tr>
    <td>
        max_connect_errors
    </td>
    <td>1000000</td>
</tr>
<tr>
    <td>
        max_delayed_threads
    </td>
    <td>20</td>
</tr>
<tr>
    <td>
        max_error_count
    </td>
    <td>64</td>
</tr>
<tr>
    <td>
        max_heap_table_size
    </td>
    <td>33554432</td>
</tr>
<tr>
    <td>
        max_insert_delayed_threads
    </td>
    <td>20</td>
</tr>
<tr>
    <td>
        max_join_size
    </td>
    <td>18446744073709551615</td>
</tr>
<tr>
    <td>
        max_length_for_sort_data
    </td>
    <td>16384</td>
</tr>
<tr>
    <td>
        max_long_data_size
    </td>
    <td>134217728</td>
</tr>
<tr>
    <td>
        max_prepared_stmt_count
    </td>
    <td>16382</td>
</tr>
<tr>
    <td>
        max_relay_log_size
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        max_seeks_for_key
    </td>
    <td>18446744073709551615</td>
</tr>
<tr>
    <td>
        max_sort_length
    </td>
    <td>1024</td>
</tr>
<tr>
    <td>
        max_sp_recursion_depth
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        max_tmp_tables
    </td>
    <td>32</td>
</tr>
<tr>
    <td>
        max_user_connections
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        max_write_lock_count
    </td>
    <td>18446744073709551615</td>
</tr>
<tr>
    <td>
        metadata_locks_cache_size
    </td>
    <td>1024</td>
</tr>
<tr>
    <td>
        min_examined_row_limit
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        multi_range_count
    </td>
    <td>256</td>
</tr>
<tr>
    <td>
        myisam_data_pointer_size
    </td>
    <td>6</td>
</tr>
<tr>
    <td>
        myisam_max_sort_file_size
    </td>
    <td>9223372036853727232</td>
</tr>
<tr>
    <td>
        myisam_mmap_size
    </td>
    <td>18446744073709551615</td>
</tr>
<tr>
    <td>
        myisam_recover_options
    </td>
    <td>DEFAULT</td>
</tr>
<tr>
    <td>
        myisam_repair_threads
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        myisam_sort_buffer_size
    </td>
    <td>67108864</td>
</tr>
<tr>
    <td>
        myisam_stats_method
    </td>
    <td>nulls_unequal</td>
</tr>
<tr>
    <td>
        myisam_use_mmap
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        net_buffer_length
    </td>
    <td>8192</td>
</tr>
<tr>
    <td>
        net_read_timeout
    </td>
    <td>30</td>
</tr>
<tr>
    <td>
        net_retry_count
    </td>
    <td>10</td>
</tr>
<tr>
    <td>
        net_write_timeout
    </td>
    <td>60</td>
</tr>
<tr>
    <td>
        new
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        old
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        old_alter_table
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        old_passwords
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        open_files_limit
    </td>
    <td>65535</td>
</tr>
<tr>
    <td>
        optimizer_prune_level
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        optimizer_search_depth
    </td>
    <td>62</td>
</tr>
<tr>
    <td>
        optimizer_switch
    </td>
    <td>index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,engine_condition_pushdown=on</td>
</tr>
<tr>
    <td>
        performance_schema
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        performance_schema_events_waits_history_long_size
    </td>
    <td>10000</td>
</tr>
<tr>
    <td>
        performance_schema_events_waits_history_size
    </td>
    <td>10</td>
</tr>
<tr>
    <td>
        performance_schema_max_cond_classes
    </td>
    <td>80</td>
</tr>
<tr>
    <td>
        performance_schema_max_cond_instances
    </td>
    <td>1000</td>
</tr>
<tr>
    <td>
        performance_schema_max_file_classes
    </td>
    <td>50</td>
</tr>
<tr>
    <td>
        performance_schema_max_file_handles
    </td>
    <td>32768</td>
</tr>
<tr>
    <td>
        performance_schema_max_file_instances
    </td>
    <td>10000</td>
</tr>
<tr>
    <td>
        performance_schema_max_mutex_classes
    </td>
    <td>200</td>
</tr>
<tr>
    <td>
        performance_schema_max_mutex_instances
    </td>
    <td>1000000</td>
</tr>
<tr>
    <td>
        performance_schema_max_rwlock_classes
    </td>
    <td>30</td>
</tr>
<tr>
    <td>
        performance_schema_max_rwlock_instances
    </td>
    <td>1000000</td>
</tr>
<tr>
    <td>
        performance_schema_max_table_handles
    </td>
    <td>100000</td>
</tr>
<tr>
    <td>
        performance_schema_max_table_instances
    </td>
    <td>50000</td>
</tr>
<tr>
    <td>
        performance_schema_max_thread_classes
    </td>
    <td>50</td>
</tr>
<tr>
    <td>
        performance_schema_max_thread_instances
    </td>
    <td>1000</td>
</tr>
<tr>
    <td>
        pid_file
    </td>
    <td>/home/woqu/data/mysqldata3306/multi-mysql.pid</td>
</tr>
<tr>
    <td>
        plugin_dir
    </td>
    <td>/home/woqu/woqu-dev-env/mysql5.5.25a/lib/plugin/</td>
</tr>
<tr>
    <td>
        port
    </td>
    <td>3306</td>
</tr>
<tr>
    <td>
        preload_buffer_size
    </td>
    <td>32768</td>
</tr>
<tr>
    <td>
        profiling
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        profiling_history_size
    </td>
    <td>15</td>
</tr>
<tr>
    <td>
        protocol_version
    </td>
    <td>10</td>
</tr>
<tr>
    <td>
        proxy_user
    </td>
    <td></td>
</tr>
<tr>
    <td>
        pseudo_thread_id
    </td>
    <td>344</td>
</tr>
<tr>
    <td>
        query_alloc_block_size
    </td>
    <td>8192</td>
</tr>
<tr>
    <td>
        query_cache_limit
    </td>
    <td>1048576</td>
</tr>
<tr>
    <td>
        query_cache_min_res_unit
    </td>
    <td>4096</td>
</tr>
<tr>
    <td>
        query_cache_size
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        query_cache_type
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        query_cache_wlock_invalidate
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        query_prealloc_size
    </td>
    <td>8192</td>
</tr>
<tr>
    <td>
        rand_seed1
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        rand_seed2
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        range_alloc_block_size
    </td>
    <td>4096</td>
</tr>
<tr>
    <td>
        read_buffer_size
    </td>
    <td>2097152</td>
</tr>
<tr>
    <td>
        read_only
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        read_rnd_buffer_size
    </td>
    <td>524288</td>
</tr>
<tr>
    <td>
        relay_log
    </td>
    <td>relay_log</td>
</tr>
<tr>
    <td>
        relay_log_index
    </td>
    <td></td>
</tr>
<tr>
    <td>
        relay_log_info_file
    </td>
    <td>relay-log.info</td>
</tr>
<tr>
    <td>
        relay_log_purge
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        relay_log_recovery
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        relay_log_space_limit
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        report_host
    </td>
    <td></td>
</tr>
<tr>
    <td>
        report_password
    </td>
    <td></td>
</tr>
<tr>
    <td>
        report_port
    </td>
    <td>3306</td>
</tr>
<tr>
    <td>
        report_user
    </td>
    <td></td>
</tr>
<tr>
    <td>
        rpl_recovery_rank
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        secure_auth
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        secure_file_priv
    </td>
    <td></td>
</tr>
<tr>
    <td>
        server_id
    </td>
    <td>1</td>
</tr>
<tr>
    <td>
        skip_external_locking
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        skip_name_resolve
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        skip_networking
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        skip_show_database
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        slave_compressed_protocol
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        slave_exec_mode
    </td>
    <td>STRICT</td>
</tr>
<tr>
    <td>
        slave_load_tmpdir
    </td>
    <td>/tmp</td>
</tr>
<tr>
    <td>
        slave_net_timeout
    </td>
    <td>3600</td>
</tr>
<tr>
    <td>
        slave_skip_errors
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        slave_transaction_retries
    </td>
    <td>10</td>
</tr>
<tr>
    <td>
        slave_type_conversions
    </td>
    <td></td>
</tr>
<tr>
    <td>
        slow_launch_time
    </td>
    <td>2</td>
</tr>
<tr>
    <td>
        slow_query_log
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        slow_query_log_file
    </td>
    <td>mysql-slow.log</td>
</tr>
<tr>
    <td>
        socket
    </td>
    <td>mysqld.sock</td>
</tr>
<tr>
    <td>
        sort_buffer_size
    </td>
    <td>2097152</td>
</tr>
<tr>
    <td>
        sql_auto_is_null
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        sql_big_selects
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        sql_big_tables
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        sql_buffer_result
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        sql_log_bin
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        sql_log_off
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        sql_low_priority_updates
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        sql_max_join_size
    </td>
    <td>18446744073709551615</td>
</tr>
<tr>
    <td>
        sql_mode
    </td>
    <td>STRICT_TRANS_TABLES</td>
</tr>
<tr>
    <td>
        sql_notes
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        sql_quote_show_create
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        sql_safe_updates
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        sql_select_limit
    </td>
    <td>18446744073709551615</td>
</tr>
<tr>
    <td>
        sql_slave_skip_counter
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        sql_warnings
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        ssl_ca
    </td>
    <td></td>
</tr>
<tr>
    <td>
        ssl_capath
    </td>
    <td></td>
</tr>
<tr>
    <td>
        ssl_cert
    </td>
    <td></td>
</tr>
<tr>
    <td>
        ssl_cipher
    </td>
    <td></td>
</tr>
<tr>
    <td>
        ssl_key
    </td>
    <td></td>
</tr>
<tr>
    <td>
        storage_engine
    </td>
    <td>InnoDB</td>
</tr>
<tr>
    <td>
        stored_program_cache
    </td>
    <td>256</td>
</tr>
<tr>
    <td>
        sync_binlog
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        sync_frm
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        sync_master_info
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        sync_relay_log
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        sync_relay_log_info
    </td>
    <td>0</td>
</tr>
<tr>
    <td>
        system_time_zone
    </td>
    <td>CST</td>
</tr>
<tr>
    <td>
        table_definition_cache
    </td>
    <td>400</td>
</tr>
<tr>
    <td>
        table_open_cache
    </td>
    <td>512</td>
</tr>
<tr>
    <td>
        thread_cache_size
    </td>
    <td>128</td>
</tr>
<tr>
    <td>
        thread_concurrency
    </td>
    <td>10</td>
</tr>
<tr>
    <td>
        thread_handling
    </td>
    <td>one-thread-per-connection</td>
</tr>
<tr>
    <td>
        thread_stack
    </td>
    <td>524288</td>
</tr>
<tr>
    <td>
        timed_mutexes
    </td>
    <td>OFF</td>
</tr>
<tr>
    <td>
        timestamp
    </td>
    <td>1400515803</td>
</tr>
<tr>
    <td>
        time_format
    </td>
    <td>%H:%i:%s</td>
</tr>
<tr>
    <td>
        time_zone
    </td>
    <td>SYSTEM</td>
</tr>
<tr>
    <td>
        tmpdir
    </td>
    <td>/tmp</td>
</tr>
<tr>
    <td>
        tmp_table_size
    </td>
    <td>33554432</td>
</tr>
<tr>
    <td>
        transaction_alloc_block_size
    </td>
    <td>8192</td>
</tr>
<tr>
    <td>
        transaction_prealloc_size
    </td>
    <td>4096</td>
</tr>
<tr>
    <td>
        tx_isolation
    </td>
    <td>READ-COMMITTED</td>
</tr>
<tr>
    <td>
        unique_checks
    </td>
    <td>ON</td>
</tr>
<tr>
    <td>
        updatable_views_with_limit
    </td>
    <td>YES</td>
</tr>
<tr>
    <td>
        version
    </td>
    <td>5.5.25a-log</td>
</tr>
<tr>
    <td>
        version_comment
    </td>
    <td>Source distribution</td>
</tr>
<tr>
    <td>
        version_compile_machine
    </td>
    <td>x86_64</td>
</tr>
<tr>
    <td>
        version_compile_os
    </td>
    <td>Linux</td>
</tr>
<tr>
    <td>
        wait_timeout
    </td>
    <td>2880000</td>
</tr>
<tr>
    <td>
        warning_count
    </td>
    <td>0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>

</div><!--/main content -->
</div>
</div><!--/container -->
<jsp:include page="../foot.jsp"/>
<script src="http://woqutech.3322.org:8080/assets/js/qm.database-instance.js?v=4.1.0.3.20140118160000"></script>
</body>
</html>

